name: mac-dev-docker    # 프로젝트 이름 추가

networks:
    default:
#      name: my-docker-default
      driver: bridge

volumes:
  my-volume:
#    name: my-volume
    driver: local

services:

  portainer-ce:
    container_name: portainer-ce
    #image: ${docker_images[portainer-ce-2.18.3]}
    image: portainer/portainer-ce:latest
    restart: always
    command: --admin-password "$$2y$$05$$fxUAxf0243TQooozoRPoUuiTsu.0Wl/iWm6syUNnDaxYhD4mQ56D."
    ports:
      - '9000:9000'
      - "9443:9443"
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/share/zoneinfo/Asia/Seoul:/etc/timezone
      - my-volume:/data

  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /usr/share/zoneinfo/Asia/Seoul:/etc/timezone
      - /etc/localtime:/etc/localtime
      - my-volume:/data
      - my-volume:/etc/letsencrypt
  postgresql:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - my-volume:/var/lib/postgresql/data