name: ${docker_prj_name} # 프로젝트 이름 추가

networks:
  default:
    name: ${docker_prj_name:-docker}-base-net
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24

volumes:
  shared-data-vol:
    driver: local

services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=maria123
      - TZ=Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - /usr/share/zoneinfo/Asia/Seoul:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /Users/danyoh/docker/volumes/our-vol/mariadb/data:/var/lib/mysql
      - /Users/danyoh/docker/volumes/our-vol/mariadb/conf.d:/etc/mysql/conf.d
      - /Users/danyoh/docker/volumes/our-vol/mariadb/script:/root/script

