name: mac-dev-docker    # 프로젝트 이름 추가

networks:
    default:
#      name: my-docker-default
      driver: bridge

volumes:
  my-volume:
#    name: my-volume
    driver: local

services:
  postgresql:
    container_name: postgres
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=postgres
      - TZ=Asia/Seoul
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - /usr/share/zoneinfo/Asia/Seoul:/etc/timezone
      - /etc/localtime:/etc/localtime
      - my-volume:/var/lib/postgresql/data