networks:
    default:
      name: my-docker-default
      driver: bridge

services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /usr/share/zoneinfo/Asia/Seoul:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /Users/danyoh/docker/volumes/our-vol/nginx-proxy-manager/data:/data
      - /Users/danyoh/docker/volumes/our-vol/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=maria123
      - TZ=Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - /usr/share/zoneinfo/Asia/Seoul:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /Users/danyoh/docker/volumes/our-vol/mariadb/data:/var/lib/mysql
      - /Users/danyoh/docker/volumes/our-vol/mariadb/conf.d:/etc/mysql/conf.d
      - /Users/danyoh/docker/volumes/our-vol/mariadb/script:/root/script

