name: mac-dev-docker    # 프로젝트 이름 추가

networks:
    default:
#      name: my-docker-default
      driver: bridge

volumes:
  my-volume:
#    name: my-volume
    driver: local

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    restart: unless-stopped
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - bootstrap.memory_lock=true
      - TZ=Asia/Seoul
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /usr/share/zoneinfo/Asia/Seoul:/etc/timezone
      - /etc/localtime:/etc/localtime
      - my-volume:/usr/share/elasticsearch/data      

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.14.0
    restart: unless-stopped
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - TZ=Asia/Seoul
    ports:
      - "5601:5601"
    volumes:
      - /usr/share/zoneinfo/Asia/Seoul:/etc/timezone
      - /etc/localtime:/etc/localtime
      - my-volume:/usr/share/kibana/data
