name: mac-dev # 프로젝트 이름 추가

networks:
  default:
    name: default_bridge
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24

volumes:
  portainer-ce-vol:
    driver: local
  shared-data-vol:
    driver: local

  portainer-ce:
    container_name: portainer-ce
    #image: ${docker_images[portainer-ce-2.18.3]}
    image: portainer/portainer-ce:latest
    restart: always
    command: --admin-password "$$2y$$05$$fxUAxf0243TQooozoRPoUuiTsu.0Wl/iWm6syUNnDaxYhD4mQ56D."
    ports:
      - "9000:9000"
      - "9443:9443"
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/share/zoneinfo/Asia/Seoul:/etc/timezone
      - portainer-ce-vol:/data

  # my spring application
  myspringapp:
    container_name: myspringapp
    image: simple-spring-boot-app
    restart: always
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/share/zoneinfo/Asia/Seoul:/etc/timezone
      - /etc/localtime:/etc/localtime
      - ${container_home}/myspringapp:/home/myspringapp
      - shared-data-vol:/shared
    entrypoint: sh /home/myspringapp/start.sh
    ports:
      - "8080:8080"
