name: mac-dev-docker    # 프로젝트 이름 추가

networks:
    default:
#      name: my-docker-default
      driver: bridge

volumes:
  my-volume:
#    name: my-volume
    driver: local

services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /usr/share/zoneinfo/Asia/Seoul:/etc/timezone
      - /etc/localtime:/etc/localtime
      - my-volume:/data
      - my-volume:/etc/letsencrypt
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=maria123
      - TZ=Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - /usr/share/zoneinfo/Asia/Seoul:/etc/timezone
      - /etc/localtime:/etc/localtime
      - my-volume:/var/lib/mysql
      - my-volume:/etc/mysql/conf.d
      - my-volume:/root/script

